import { LanguageCode } from './siteNavigation'

type HubPageKey = 'rates' | 'pairs' | 'transfer' | 'privacy'

export const HUB_TEXT: Record<HubPageKey, Record<LanguageCode, {
  title: string
  description: string
  eyebrow: string
  heading: string
  body: string
  cardsHeading: string
  cards: Array<{ title: string; body: string; href?: string }>
  linksHeading: string
  contentHeading: string
  paragraphs: string[]
}>> = {
  rates: {
    th: {
      title: 'อัตราแลกเปลี่ยนวันนี้ ทุกสกุลเงินยอดนิยม',
      description: 'รวมอัตราแลกเปลี่ยนวันนี้สำหรับ THB, USD, USDT, EUR, JPY, LAK, MMK, KHR และสกุลเงินยอดนิยม พร้อมลิงก์ไปหน้าคู่เงินสำคัญ',
      eyebrow: 'Exchange rate hub',
      heading: 'อัตราแลกเปลี่ยนวันนี้สำหรับสกุลเงินหลักและสกุลเงินอาเซียน',
      body: 'รวมทางเข้าไปยังเรทสดและหน้าคำนวณคู่เงินที่คนค้นหาบ่อย ใช้เช็กเงินบาท ดอลลาร์ USDT ยูโร เยน กีบ จ๊าต และเรียลก่อนแลกเงินหรือโอนเงิน',
      cardsHeading: 'เรทที่ควรเช็กบ่อย',
      cards: [
        { title: 'USD/THB', body: 'ดอลลาร์สหรัฐเทียบเงินบาท สำหรับดูค่าเงินดอลลาร์วันนี้', href: '/usd-thb' },
        { title: 'USDT/THB', body: 'USDT เทียบเงินบาท สำหรับประเมินมูลค่า stablecoin', href: '/usdt-thb' },
        { title: 'THB/MMK', body: 'เงินบาทเทียบจ๊าตเมียนมา สำหรับค่าใช้จ่ายและการโอนเงิน', href: '/thb-mmk' },
      ],
      linksHeading: 'คู่เงินอัตราแลกเปลี่ยนทั้งหมด',
      contentHeading: 'ใช้หน้าอัตราแลกเปลี่ยนอย่างไรให้คุ้ม',
      paragraphs: ['เริ่มจากเลือกคู่เงินที่เกี่ยวกับธุรกรรมของคุณ เช่น USD/THB สำหรับดอลลาร์, THB/LAK สำหรับไทย-ลาว หรือ THB/MMK สำหรับไทย-เมียนมา', 'ตัวเลขบน zrate.io เหมาะสำหรับอ้างอิงเบื้องต้น ก่อนทำธุรกรรมจริงควรเทียบกับเรทธนาคาร ร้านแลกเงิน หรือผู้ให้บริการโอนเงินอีกครั้ง'],
    },
    en: {
      title: 'Live Exchange Rates Today for Major Currencies',
      description: 'Browse today’s exchange rates for THB, USD, USDT, EUR, JPY, LAK, MMK, KHR and popular currency pairs with direct links to live pair pages.',
      eyebrow: 'Exchange rate hub',
      heading: 'Today’s exchange rates for major and Southeast Asian currencies',
      body: 'Find live-rate entry points for popular currency searches, including Thai baht, US dollars, USDT, euros, yen, Lao kip, Myanmar kyat and Cambodian riel.',
      cardsHeading: 'Rates to check often',
      cards: [
        { title: 'USD/THB', body: 'US dollar to Thai baht for checking today’s dollar rate.', href: '/usd-thb' },
        { title: 'USDT/THB', body: 'USDT to Thai baht for stablecoin reference pricing.', href: '/usdt-thb' },
        { title: 'THB/MMK', body: 'Thai baht to Myanmar kyat for expenses and transfers.', href: '/thb-mmk' },
      ],
      linksHeading: 'All exchange-rate pairs',
      contentHeading: 'How to use this rates hub',
      paragraphs: ['Start with the pair that matches your transaction, such as USD/THB for dollars, THB/LAK for Thailand-Laos, or THB/MMK for Thailand-Myanmar.', 'Rates on zrate.io are reference values. Always compare with your bank, exchange shop, or remittance provider before making a real transaction.'],
    },
    lo: {
      title: 'ອັດຕາແລກປ່ຽນມື້ນີ້ ສະກຸນເງິນຍອດນິຍົມ',
      description: 'ລວມອັດຕາແລກປ່ຽນ THB, USD, USDT, EUR, JPY, LAK, MMK, KHR ແລະຄູ່ເງິນສຳຄັນ',
      eyebrow: 'Exchange rate hub',
      heading: 'ອັດຕາແລກປ່ຽນມື້ນີ້ສຳລັບສະກຸນເງິນຫຼັກແລະອາຊຽນ',
      body: 'ທາງເຂົ້າໄປຫາເຣດສົດຂອງຄູ່ເງິນທີ່ຄົນຄົ້ນຫາບ່ອຍ ເຊັ່ນ ບາດ ໂດລາ USDT ກີບ ຈາດ ແລະຣຽວ',
      cardsHeading: 'ເຣດທີ່ຄວນເບິ່ງບ່ອຍ',
      cards: [
        { title: 'USD/LAK', body: 'ໂດລາສະຫະລັດທຽບກີບລາວ', href: '/usd-lak' },
        { title: 'THB/LAK', body: 'ບາດໄທທຽບກີບລາວ', href: '/thb-lak' },
        { title: 'USD/THB', body: 'ໂດລາສະຫະລັດທຽບບາດໄທ', href: '/usd-thb' },
      ],
      linksHeading: 'ຄູ່ເງິນທັງໝົດ',
      contentHeading: 'ວິທີໃຊ້ໜ້າອັດຕາແລກປ່ຽນ',
      paragraphs: ['ເລືອກຄູ່ເງິນທີ່ກົງກັບການໃຊ້ງານຂອງທ່ານ ເຊັ່ນ THB/LAK ຫຼື USD/LAK', 'ອັດຕາໃນ zrate.io ແມ່ນຂໍ້ມູນອ້າງອີງ ຄວນກວດກັບຜູ້ໃຫ້ບໍລິການກ່ອນເຮັດທຸລະກຳຈິງ'],
    },
    my: {
      title: 'ယနေ့ ငွေလဲနှုန်းများ',
      description: 'THB, USD, USDT, EUR, JPY, LAK, MMK, KHR နှင့် လူကြိုက်များသော ငွေကြေးအတွဲများ၏ ယနေ့နှုန်းများ',
      eyebrow: 'Exchange rate hub',
      heading: 'အဓိကငွေကြေးများနှင့် အာဆီယံငွေကြေးများအတွက် ယနေ့ငွေလဲနှုန်းများ',
      body: 'ဘတ်၊ ဒေါ်လာ၊ USDT၊ ယူရို၊ ယန်း၊ ကျပ်၊ ကီပ် နှင့် ရီယယ်အတွက် လူရှာများသော တိုက်ရိုက်နှုန်းစာမျက်နှာများကို စုစည်းထားသည်',
      cardsHeading: 'မကြာခဏစစ်သင့်သောနှုန်းများ',
      cards: [
        { title: 'THB/MMK', body: 'ထိုင်းဘတ်မှ မြန်မာကျပ်သို့', href: '/thb-mmk' },
        { title: 'USD/MMK', body: 'ဒေါ်လာမှ မြန်မာကျပ်သို့', href: '/usd-mmk' },
        { title: 'USD/THB', body: 'ဒေါ်လာမှ ထိုင်းဘတ်သို့', href: '/usd-thb' },
      ],
      linksHeading: 'ငွေကြေးအတွဲအားလုံး',
      contentHeading: 'နှုန်းစာမျက်နှာကိုအသုံးပြုနည်း',
      paragraphs: ['သင်လုပ်မည့်ငွေလဲခြင်း သို့မဟုတ် ငွေလွှဲခြင်းနှင့်ကိုက်ညီသော အတွဲကိုရွေးပါ', 'zrate.io ပေါ်ရှိနှုန်းများသည် ကိုးကားရန်ဖြစ်ပြီး တကယ်အသုံးပြုမည့်ဝန်ဆောင်မှု၏နှုန်းနှင့် ထပ်မံနှိုင်းယှဉ်သင့်သည်'],
    },
    km: {
      title: 'អត្រាប្តូរប្រាក់ថ្ងៃនេះ',
      description: 'អត្រាប្តូរប្រាក់សម្រាប់ THB, USD, USDT, EUR, JPY, LAK, MMK, KHR និងគូរូបិយប័ណ្ណពេញនិយម',
      eyebrow: 'Exchange rate hub',
      heading: 'អត្រាប្តូរប្រាក់ថ្ងៃនេះសម្រាប់រូបិយប័ណ្ណសំខាន់ៗ និងអាស៊ាន',
      body: 'ច្រកចូលទៅកាន់អត្រាផ្ទាល់សម្រាប់បាត ដុល្លារ USDT អឺរ៉ូ យ៉េន គីប គ្យាត និងរៀល',
      cardsHeading: 'អត្រាដែលគួរពិនិត្យញឹកញាប់',
      cards: [
        { title: 'THB/KHR', body: 'ប្រាក់បាតថៃទៅរៀលកម្ពុជា', href: '/thb-khr' },
        { title: 'USD/KHR', body: 'ដុល្លារអាមេរិកទៅរៀលកម្ពុជា', href: '/usd-khr' },
        { title: 'USD/THB', body: 'ដុល្លារអាមេរិកទៅប្រាក់បាតថៃ', href: '/usd-thb' },
      ],
      linksHeading: 'គូរូបិយប័ណ្ណទាំងអស់',
      contentHeading: 'របៀបប្រើមជ្ឈមណ្ឌលអត្រា',
      paragraphs: ['ជ្រើសរើសគូរូបិយប័ណ្ណដែលត្រូវនឹងការប្រើប្រាស់របស់អ្នក ដូចជា THB/KHR ឬ USD/KHR', 'អត្រានៅលើ zrate.io គឺសម្រាប់យោងប៉ុណ្ណោះ គួរប្រៀបធៀបជាមួយធនាគារ ឬអ្នកផ្តល់សេវាមុនធ្វើប្រតិបត្តិការពិត'],
    },
  },
  pairs: {
    th: {
      title: 'คู่เงินทั้งหมด USD THB USDT LAK MMK KHR',
      description: 'รวมหน้าคู่สกุลเงินทั้งหมดของ zrate.io สำหรับค้นหาเรท USD/THB, USDT/THB, THB/LAK, THB/MMK, THB/KHR และอีกหลายคู่',
      eyebrow: 'Currency pair directory',
      heading: 'คู่เงินทั้งหมดบน zrate.io',
      body: 'ไดเรกทอรีคู่สกุลเงินสำหรับเข้าหน้าเรทเฉพาะคู่โดยตรง เหมาะกับคำค้นหาแบบเจาะจง เช่น ดอลลาร์เป็นบาท หรือเงินบาทเป็นจ๊าต',
      cardsHeading: 'หมวดคู่เงินสำคัญ',
      cards: [
        { title: 'คู่เงินเงินบาท', body: 'USD/THB, EUR/THB, USDT/THB และคู่เงินบาทหลัก', href: '/usd-thb' },
        { title: 'คู่เงินประเทศเพื่อนบ้าน', body: 'THB/LAK, THB/MMK, THB/KHR สำหรับอาเซียน', href: '/thb-lak' },
        { title: 'คู่เงินเอเชีย', body: 'JPY/THB, CNY/THB, SGD/THB, KRW/THB', href: '/jpy-thb' },
      ],
      linksHeading: 'เลือกคู่เงิน',
      contentHeading: 'ทำไมต้องมีหน้าคู่เงินเฉพาะ',
      paragraphs: ['หน้าคู่เงินเฉพาะช่วยให้ผู้ใช้และ Google เข้าใจคำตอบของคำค้นหาแบบตรงตัว เช่น 1 USD เท่ากับกี่บาท หรือ 1000 บาทเท่ากับกี่จ๊าต', 'ทุกหน้าคู่เงินควรเชื่อมกลับมาหน้านี้และเชื่อมไปคู่เงินใกล้เคียง เพื่อสร้างโครง internal linking ที่แข็งแรง'],
    },
    en: {
      title: 'All Currency Pairs: USD THB USDT LAK MMK KHR',
      description: 'Browse all zrate.io currency-pair pages, including USD/THB, USDT/THB, THB/LAK, THB/MMK, THB/KHR and more.',
      eyebrow: 'Currency pair directory',
      heading: 'All currency pairs on zrate.io',
      body: 'A directory for direct access to dedicated exchange-rate pages, useful for specific searches such as dollar to baht or Thai baht to Myanmar kyat.',
      cardsHeading: 'Important pair groups',
      cards: [
        { title: 'Thai baht pairs', body: 'USD/THB, EUR/THB, USDT/THB and key baht pairs.', href: '/usd-thb' },
        { title: 'Neighboring-country pairs', body: 'THB/LAK, THB/MMK and THB/KHR for regional use.', href: '/thb-lak' },
        { title: 'Asian pairs', body: 'JPY/THB, CNY/THB, SGD/THB and KRW/THB.', href: '/jpy-thb' },
      ],
      linksHeading: 'Choose a currency pair',
      contentHeading: 'Why dedicated pair pages matter',
      paragraphs: ['Dedicated pair pages answer exact search intent, such as how many baht one US dollar equals or how many kyat 1,000 baht equals.', 'Each pair page should link back to this directory and nearby related pairs to build a stronger internal-link structure.'],
    },
    lo: {
      title: 'ຄູ່ເງິນທັງໝົດ USD THB USDT LAK MMK KHR',
      description: 'ລວມຄູ່ເງິນທັງໝົດໃນ zrate.io ເຊັ່ນ USD/THB, THB/LAK, USD/LAK',
      eyebrow: 'Currency pair directory',
      heading: 'ຄູ່ເງິນທັງໝົດໃນ zrate.io',
      body: 'ລາຍຊື່ຄູ່ເງິນສຳລັບເຂົ້າໄປໜ້າເຣດສະເພາະຄູ່ໄດ້ໂດຍກົງ',
      cardsHeading: 'ກຸ່ມຄູ່ເງິນສຳຄັນ',
      cards: [
        { title: 'ຄູ່ເງິນບາດ', body: 'USD/THB, EUR/THB ແລະ USDT/THB', href: '/usd-thb' },
        { title: 'ຄູ່ເງິນລາວ', body: 'THB/LAK ແລະ USD/LAK', href: '/thb-lak' },
        { title: 'ຄູ່ເງິນອາຊຽນ', body: 'THB/MMK, THB/KHR ແລະ USD/KHR', href: '/thb-mmk' },
      ],
      linksHeading: 'ເລືອກຄູ່ເງິນ',
      contentHeading: 'ເຫດໃດຈຶ່ງຕ້ອງມີໜ້າຄູ່ເງິນສະເພາະ',
      paragraphs: ['ໜ້າຄູ່ເງິນຊ່ວຍຕອບຄຳຖາມແບບຈົງເຈາະ ເຊັ່ນ 1 ໂດລາເທົ່າກັບຈັກກີບ', 'ການເຊື່ອມລິ້ງລະຫວ່າງຄູ່ເງິນໃກ້ຄຽງຊ່ວຍໃຫ້ເວັບຖືກ crawl ດີຂຶ້ນ'],
    },
    my: {
      title: 'ငွေကြေးအတွဲအားလုံး USD THB USDT LAK MMK KHR',
      description: 'USD/THB, USDT/THB, THB/MMK, USD/MMK နှင့် zrate.io ပေါ်ရှိ ငွေကြေးအတွဲအားလုံး',
      eyebrow: 'Currency pair directory',
      heading: 'zrate.io ပေါ်ရှိ ငွေကြေးအတွဲအားလုံး',
      body: 'သီးခြားငွေလဲနှုန်းစာမျက်နှာများသို့ တိုက်ရိုက်ဝင်နိုင်ရန် ငွေကြေးအတွဲလမ်းညွှန်',
      cardsHeading: 'အရေးကြီးသောအတွဲအုပ်စုများ',
      cards: [
        { title: 'ထိုင်းဘတ်အတွဲများ', body: 'USD/THB, EUR/THB, USDT/THB', href: '/usd-thb' },
        { title: 'မြန်မာကျပ်အတွဲများ', body: 'THB/MMK နှင့် USD/MMK', href: '/thb-mmk' },
        { title: 'အာဆီယံအတွဲများ', body: 'THB/LAK, THB/KHR, USD/KHR', href: '/thb-lak' },
      ],
      linksHeading: 'ငွေကြေးအတွဲရွေးပါ',
      contentHeading: 'သီးခြားအတွဲစာမျက်နှာများအရေးကြီးသောအကြောင်း',
      paragraphs: ['သီးခြားအတွဲစာမျက်နှာသည် 1 ဒေါ်လာဘတ်ဘယ်လောက် သို့မဟုတ် 1000 ဘတ်ကျပ်ဘယ်လောက်ကဲ့သို့ တိကျသောရှာဖွေမှုကို ဖြေဆိုနိုင်သည်', 'ဆက်စပ်အတွဲများသို့ လင့်ခ်ချိတ်ခြင်းသည် crawl နှင့် SEO ဖွဲ့စည်းပုံကို အားကောင်းစေသည်'],
    },
    km: {
      title: 'គូរូបិយប័ណ្ណទាំងអស់ USD THB USDT LAK MMK KHR',
      description: 'បញ្ជីគូរូបិយប័ណ្ណទាំងអស់នៅ zrate.io រួមមាន USD/THB, USDT/THB, THB/KHR និង USD/KHR',
      eyebrow: 'Currency pair directory',
      heading: 'គូរូបិយប័ណ្ណទាំងអស់នៅ zrate.io',
      body: 'បញ្ជីសម្រាប់ចូលទៅទំព័រអត្រាប្តូរប្រាក់ជាក់លាក់តាមគូរូបិយប័ណ្ណ',
      cardsHeading: 'ក្រុមគូរូបិយប័ណ្ណសំខាន់',
      cards: [
        { title: 'គូប្រាក់បាត', body: 'USD/THB, EUR/THB, USDT/THB', href: '/usd-thb' },
        { title: 'គូរៀលកម្ពុជា', body: 'THB/KHR និង USD/KHR', href: '/thb-khr' },
        { title: 'គូអាស៊ាន', body: 'THB/LAK, THB/MMK, USD/MMK', href: '/thb-lak' },
      ],
      linksHeading: 'ជ្រើសរើសគូរូបិយប័ណ្ណ',
      contentHeading: 'ហេតុអ្វីទំព័រគូរូបិយប័ណ្ណសំខាន់',
      paragraphs: ['ទំព័រគូរូបិយប័ណ្ណជួយឆ្លើយសំណួរជាក់លាក់ ដូចជា 1 ដុល្លារស្មើប៉ុន្មានបាត', 'ការភ្ជាប់ទៅគូដែលពាក់ព័ន្ធជួយឱ្យរចនាសម្ព័ន្ធ internal linking រឹងមាំ'],
    },
  },
  transfer: {
    th: {
      title: 'คู่มือโอนเงินต่างประเทศและเทียบเรทโอนเงิน',
      description: 'คู่มือโอนเงินต่างประเทศ เทียบเรทและค่าธรรมเนียมสำหรับไทย ลาว เมียนมา กัมพูชา พร้อมลิงก์ไปเรทคู่เงินที่ใช้คำนวณต้นทุน',
      eyebrow: 'Money transfer guide',
      heading: 'โอนเงินต่างประเทศให้คุ้ม ต้องเทียบทั้งค่าธรรมเนียมและเรท',
      body: 'หน้า hub สำหรับบทความโอนเงินและคู่เงินที่เกี่ยวข้อง เหมาะกับผู้ใช้ที่ต้องการส่งเงินระหว่างไทย ลาว เมียนมา และกัมพูชา',
      cardsHeading: 'คู่เงินที่ใช้คำนวณค่าโอน',
      cards: [
        { title: 'THB/MMK', body: 'ใช้ประเมินยอดรับปลายทางเมียนมา', href: '/thb-mmk' },
        { title: 'THB/LAK', body: 'ใช้เทียบค่าโอนและค่าใช้จ่ายไทย-ลาว', href: '/thb-lak' },
        { title: 'THB/KHR', body: 'ใช้ประเมินค่าใช้จ่ายไทย-กัมพูชา', href: '/thb-khr' },
      ],
      linksHeading: 'เรทที่เกี่ยวกับการโอนเงิน',
      contentHeading: 'สูตรคิดต้นทุนโอนเงิน',
      paragraphs: ['ต้นทุนรวมของการโอนเงินไม่ได้มีแค่ค่าธรรมเนียม แต่รวมส่วนต่างเรทที่ผู้ให้บริการบวกไว้ด้วย', 'ก่อนโอนให้เทียบจำนวนเงินปลายทางที่ผู้รับจะได้จริงกับเรทอ้างอิงบน zrate.io เพื่อดูว่าช่องทางไหนคุ้มกว่า'],
    },
    en: {
      title: 'International Money Transfer Guides and Rate Comparison',
      description: 'Money transfer guides for Thailand, Laos, Myanmar and Cambodia with exchange-rate links for calculating total transfer costs.',
      eyebrow: 'Money transfer guide',
      heading: 'Compare both fees and exchange rates before sending money',
      body: 'A hub for remittance articles and related exchange-rate pages, built for users sending money across Thailand, Laos, Myanmar and Cambodia.',
      cardsHeading: 'Pairs used for transfer estimates',
      cards: [
        { title: 'THB/MMK', body: 'Estimate receiving amounts for Myanmar transfers.', href: '/thb-mmk' },
        { title: 'THB/LAK', body: 'Compare Thailand-Laos transfer and expense values.', href: '/thb-lak' },
        { title: 'THB/KHR', body: 'Estimate Thailand-Cambodia costs.', href: '/thb-khr' },
      ],
      linksHeading: 'Rates related to remittance',
      contentHeading: 'How to estimate transfer cost',
      paragraphs: ['The total cost of a money transfer is not only the displayed fee. It also includes the exchange-rate margin added by the provider.', 'Before sending money, compare the real receiving amount with reference rates on zrate.io to see which channel is more cost-effective.'],
    },
    lo: {
      title: 'ຄູ່ມືໂອນເງິນຕ່າງປະເທດ',
      description: 'ຄູ່ມືໂອນເງິນ ແລະການທຽບເຣດສຳລັບໄທ ລາວ ມຽນມາ ແລະກຳປູເຈຍ',
      eyebrow: 'Money transfer guide',
      heading: 'ກ່ອນໂອນເງິນຄວນທຽບທັງຄ່າທຳນຽມແລະເຣດ',
      body: 'ສູນລວມບົດຄວາມໂອນເງິນ ແລະຄູ່ເງິນທີ່ກ່ຽວຂ້ອງໃນພາກພື້ນ',
      cardsHeading: 'ຄູ່ເງິນສຳລັບຄຳນວນຄ່າໂອນ',
      cards: [
        { title: 'THB/LAK', body: 'ປະເມີນຍອດຮັບລະຫວ່າງໄທ-ລາວ', href: '/thb-lak' },
        { title: 'USD/LAK', body: 'ທຽບໂດລາກັບກີບ', href: '/usd-lak' },
        { title: 'THB/MMK', body: 'ອ້າງອີງການໂອນໄປມຽນມາ', href: '/thb-mmk' },
      ],
      linksHeading: 'ເຣດທີ່ກ່ຽວກັບການໂອນ',
      contentHeading: 'ວິທີຄິດຕົ້ນທຶນໂອນເງິນ',
      paragraphs: ['ຕົ້ນທຶນລວມມີທັງຄ່າທຳນຽມ ແລະສ່ວນຕ່າງອັດຕາແລກປ່ຽນ', 'ກ່ອນໂອນຄວນທຽບຈຳນວນເງິນປາຍທາງກັບເຣດອ້າງອີງໃນ zrate.io'],
    },
    my: {
      title: 'နိုင်ငံတကာငွေလွှဲလမ်းညွှန်',
      description: 'ထိုင်း၊ လာအို၊ မြန်မာ၊ ကမ္ဘောဒီးယားအတွက် ငွေလွှဲနှင့် ငွေလဲနှုန်းနှိုင်းယှဉ်လမ်းညွှန်',
      eyebrow: 'Money transfer guide',
      heading: 'ငွေလွှဲမလုပ်ခင် ဝန်ဆောင်ခနှင့် ငွေလဲနှုန်းနှစ်ခုလုံးကို နှိုင်းယှဉ်ပါ',
      body: 'ထိုင်း၊ လာအို၊ မြန်မာနှင့် ကမ္ဘောဒီးယားအတွက် ငွေလွှဲဆောင်းပါးများနှင့် သက်ဆိုင်သောနှုန်းစာမျက်နှာများစုစည်းထားသည်',
      cardsHeading: 'ငွေလွှဲတွက်ချက်ရန်သုံးသောအတွဲများ',
      cards: [
        { title: 'THB/MMK', body: 'မြန်မာသို့လွှဲငွေအတွက် လက်ခံရမည့်ပမာဏခန့်မှန်းရန်', href: '/thb-mmk' },
        { title: 'USD/MMK', body: 'ဒေါ်လာနှင့်ကျပ်နှိုင်းယှဉ်ရန်', href: '/usd-mmk' },
        { title: 'THB/LAK', body: 'ဒေသတွင်းနှုန်းနှိုင်းယှဉ်ရန်', href: '/thb-lak' },
      ],
      linksHeading: 'ငွေလွှဲနှင့်သက်ဆိုင်သောနှုန်းများ',
      contentHeading: 'ငွေလွှဲကုန်ကျစရိတ်တွက်ချက်နည်း',
      paragraphs: ['ငွေလွှဲကုန်ကျစရိတ်တွင် ဖော်ပြထားသောဝန်ဆောင်ခအပြင် ငွေလဲနှုန်းကွာဟချက်လည်းပါဝင်သည်', 'မလွှဲမီ လက်ခံသူရမည့်ပမာဏကို zrate.io ပေါ်ရှိကိုးကားနှုန်းနှင့် နှိုင်းယှဉ်သင့်သည်'],
    },
    km: {
      title: 'មគ្គុទ្ទេសក៍ផ្ទេរប្រាក់អន្តរជាតិ',
      description: 'មគ្គុទ្ទេសក៍ផ្ទេរប្រាក់ និងប្រៀបធៀបអត្រាសម្រាប់ថៃ ឡាវ មីយ៉ាន់ម៉ា និងកម្ពុជា',
      eyebrow: 'Money transfer guide',
      heading: 'មុនផ្ទេរប្រាក់ គួរប្រៀបធៀបទាំងថ្លៃសេវា និងអត្រាប្តូរ',
      body: 'មជ្ឈមណ្ឌលសម្រាប់អត្ថបទផ្ទេរប្រាក់ និងទំព័រអត្រាដែលពាក់ព័ន្ធនៅក្នុងតំបន់',
      cardsHeading: 'គូរូបិយប័ណ្ណសម្រាប់គណនាការផ្ទេរ',
      cards: [
        { title: 'THB/KHR', body: 'ប៉ាន់ស្មានចំនួនប្រាក់ទទួលសម្រាប់ថៃ-កម្ពុជា', href: '/thb-khr' },
        { title: 'USD/KHR', body: 'ប្រៀបធៀបដុល្លារជាមួយរៀល', href: '/usd-khr' },
        { title: 'THB/MMK', body: 'យោងសម្រាប់ការផ្ទេរទៅមីយ៉ាន់ម៉ា', href: '/thb-mmk' },
      ],
      linksHeading: 'អត្រាដែលពាក់ព័ន្ធនឹងការផ្ទេរ',
      contentHeading: 'របៀបគណនាថ្លៃដើមផ្ទេរប្រាក់',
      paragraphs: ['ថ្លៃដើមសរុបរួមមានថ្លៃសេវា និងភាពខុសគ្នានៃអត្រាប្តូរប្រាក់', 'មុនផ្ទេរ គួរប្រៀបធៀបចំនួនប្រាក់ដែលអ្នកទទួលនឹងបានជាមួយអត្រាយោងនៅ zrate.io'],
    },
  },
  privacy: {
    th: {
      title: 'นโยบายความเป็นส่วนตัว',
      description: 'นโยบายความเป็นส่วนตัวของ zrate.io เกี่ยวกับข้อมูลการใช้งาน คุกกี้ โฆษณา และแหล่งข้อมูลอัตราแลกเปลี่ยน',
      eyebrow: 'Privacy',
      heading: 'นโยบายความเป็นส่วนตัว',
      body: 'zrate.io ให้ความสำคัญกับความโปร่งใสของข้อมูล หน้านี้อธิบายข้อมูลที่เว็บไซต์อาจใช้เพื่อให้บริการอัตราแลกเปลี่ยนและปรับปรุงประสบการณ์ผู้ใช้',
      cardsHeading: 'หัวข้อสำคัญ',
      cards: [
        { title: 'ข้อมูลการใช้งาน', body: 'เราอาจใช้ข้อมูลเชิงเทคนิคเพื่อวิเคราะห์ประสิทธิภาพของเว็บไซต์' },
        { title: 'คุกกี้และโฆษณา', body: 'บริการโฆษณาหรือวิเคราะห์อาจใช้คุกกี้ตามนโยบายของผู้ให้บริการนั้น' },
        { title: 'ข้อมูลอัตราแลกเปลี่ยน', body: 'ข้อมูลเรทมาจากแหล่งข้อมูลภายนอกและใช้เพื่ออ้างอิงเท่านั้น' },
      ],
      linksHeading: 'หน้าที่เกี่ยวข้อง',
      contentHeading: 'รายละเอียดนโยบาย',
      paragraphs: ['เราไม่ขอข้อมูลการเงินส่วนตัว เช่น เลขบัญชี รหัสผ่าน หรือข้อมูลบัตรชำระเงิน ผ่านหน้าแปลงค่าเงิน', 'หากมีการใช้เครื่องมือวิเคราะห์หรือโฆษณา ข้อมูลอาจถูกประมวลผลโดยผู้ให้บริการภายนอกตามนโยบายของบริการนั้น', 'ผู้ใช้ควรตรวจสอบเรทจริงกับธนาคาร ร้านแลกเงิน หรือผู้ให้บริการโอนเงินก่อนทำธุรกรรม'],
    },
    en: {
      title: 'Privacy Policy',
      description: 'zrate.io privacy policy covering usage data, cookies, advertising and exchange-rate data sources.',
      eyebrow: 'Privacy',
      heading: 'Privacy Policy',
      body: 'zrate.io values transparency. This page explains the information the site may use to provide exchange-rate tools and improve user experience.',
      cardsHeading: 'Key topics',
      cards: [
        { title: 'Usage data', body: 'Technical usage data may be used to analyze site performance.' },
        { title: 'Cookies and ads', body: 'Advertising or analytics services may use cookies under their own policies.' },
        { title: 'Exchange-rate data', body: 'Rates come from external data sources and are provided for reference only.' },
      ],
      linksHeading: 'Related pages',
      contentHeading: 'Policy details',
      paragraphs: ['We do not ask for private financial details such as account numbers, passwords or payment-card data through the currency converter.', 'If analytics or advertising tools are used, information may be processed by external providers under their own policies.', 'Users should verify actual rates with banks, exchange shops or remittance providers before making transactions.'],
    },
    lo: {
      title: 'ນະໂຍບາຍຄວາມລັບ',
      description: 'ນະໂຍບາຍຄວາມລັບຂອງ zrate.io ກ່ຽວກັບຂໍ້ມູນການໃຊ້ງານ cookies ແລະຂໍ້ມູນອັດຕາແລກປ່ຽນ',
      eyebrow: 'Privacy',
      heading: 'ນະໂຍບາຍຄວາມລັບ',
      body: 'zrate.io ໃຫ້ຄວາມສຳຄັນກັບຄວາມໂປ່ງໃສຂອງຂໍ້ມູນ',
      cardsHeading: 'ຫົວຂໍ້ສຳຄັນ',
      cards: [
        { title: 'ຂໍ້ມູນການໃຊ້ງານ', body: 'ອາດໃຊ້ຂໍ້ມູນເຊິງເຕັກນິກເພື່ອວິເຄາະເວັບ' },
        { title: 'Cookies ແລະໂຄສະນາ', body: 'ຜູ້ໃຫ້ບໍລິການພາຍນອກອາດໃຊ້ cookies' },
        { title: 'ຂໍ້ມູນເຣດ', body: 'ອັດຕາແມ່ນຂໍ້ມູນອ້າງອີງຈາກແຫຼ່ງພາຍນອກ' },
      ],
      linksHeading: 'ໜ້າທີ່ກ່ຽວຂ້ອງ',
      contentHeading: 'ລາຍລະອຽດ',
      paragraphs: ['ພວກເຮົາບໍ່ຂໍເລກບັນຊີ ລະຫັດຜ່ານ ຫຼືຂໍ້ມູນບັດຊຳລະເງິນ', 'ຂໍ້ມູນອາດຖືກປະມວນຜົນໂດຍບໍລິການວິເຄາະ ຫຼືໂຄສະນາພາຍນອກ', 'ຄວນກວດເຣດຈິງກັບຜູ້ໃຫ້ບໍລິການກ່ອນທຸລະກຳ'],
    },
    my: {
      title: 'ကိုယ်ရေးလုံခြုံရေးမူဝါဒ',
      description: 'zrate.io ၏ အသုံးပြုမှုဒေတာ၊ cookies၊ ကြော်ငြာနှင့် ငွေလဲနှုန်းဒေတာရင်းမြစ်ဆိုင်ရာ မူဝါဒ',
      eyebrow: 'Privacy',
      heading: 'ကိုယ်ရေးလုံခြုံရေးမူဝါဒ',
      body: 'zrate.io သည် ဒေတာအသုံးပြုမှုကို ပွင့်လင်းမြင်သာစေရန် အရေးကြီးဟုယူဆသည်',
      cardsHeading: 'အဓိကအကြောင်းအရာများ',
      cards: [
        { title: 'အသုံးပြုမှုဒေတာ', body: 'ဝဘ်ဆိုက်စွမ်းဆောင်ရည်ကိုခွဲခြမ်းစိတ်ဖြာရန် နည်းပညာဆိုင်ရာဒေတာကို အသုံးပြုနိုင်သည်' },
        { title: 'Cookies နှင့် ကြော်ငြာ', body: 'ပြင်ပဝန်ဆောင်မှုများသည် ၎င်းတို့၏မူဝါဒအရ cookies ကိုအသုံးပြုနိုင်သည်' },
        { title: 'ငွေလဲနှုန်းဒေတာ', body: 'နှုန်းများသည် ပြင်ပရင်းမြစ်မှဖြစ်ပြီး ကိုးကားရန်သာဖြစ်သည်' },
      ],
      linksHeading: 'သက်ဆိုင်သောစာမျက်နှာများ',
      contentHeading: 'မူဝါဒအသေးစိတ်',
      paragraphs: ['ကျွန်ုပ်တို့သည် အကောင့်နံပါတ်၊ စကားဝှက် သို့မဟုတ် ငွေပေးချေကတ်ဒေတာများကို converter မှတဆင့် မတောင်းပါ', 'Analytics သို့မဟုတ် ကြော်ငြာကိရိယာများအသုံးပြုပါက ပြင်ပဝန်ဆောင်မှုပေးသူများက ၎င်းတို့၏မူဝါဒအရ ဒေတာကိုလုပ်ဆောင်နိုင်သည်', 'တကယ်ငွေလဲခြင်းမပြုမီ ဘဏ် သို့မဟုတ် ဝန်ဆောင်မှုပေးသူနှင့် နှုန်းကိုစစ်ဆေးသင့်သည်'],
    },
    km: {
      title: 'គោលការណ៍ឯកជនភាព',
      description: 'គោលការណ៍ឯកជនភាព zrate.io ស្តីពីទិន្នន័យប្រើប្រាស់ cookies ការផ្សាយពាណិជ្ជកម្ម និងប្រភពទិន្នន័យអត្រាប្តូរ',
      eyebrow: 'Privacy',
      heading: 'គោលការណ៍ឯកជនភាព',
      body: 'zrate.io ផ្តល់សារៈសំខាន់ដល់ភាពថ្លៃថ្នូរនៃការប្រើប្រាស់ទិន្នន័យ',
      cardsHeading: 'ប្រធានបទសំខាន់',
      cards: [
        { title: 'ទិន្នន័យប្រើប្រាស់', body: 'អាចប្រើទិន្នន័យបច្ចេកទេសសម្រាប់វិភាគដំណើរការគេហទំព័រ' },
        { title: 'Cookies និងពាណិជ្ជកម្ម', body: 'សេវាខាងក្រៅអាចប្រើ cookies តាមគោលការណ៍របស់ពួកគេ' },
        { title: 'ទិន្នន័យអត្រា', body: 'អត្រាមកពីប្រភពខាងក្រៅ និងសម្រាប់យោងប៉ុណ្ណោះ' },
      ],
      linksHeading: 'ទំព័រពាក់ព័ន្ធ',
      contentHeading: 'ព័ត៌មានលម្អិត',
      paragraphs: ['យើងមិនស្នើសុំលេខគណនី ពាក្យសម្ងាត់ ឬទិន្នន័យកាតទូទាត់តាមឧបករណ៍បម្លែងប្រាក់ឡើយ', 'ប្រសិនបើប្រើឧបករណ៍វិភាគ ឬពាណិជ្ជកម្ម ទិន្នន័យអាចត្រូវបានដំណើរការដោយអ្នកផ្តល់សេវាខាងក្រៅ', 'គួរពិនិត្យអត្រាពិតជាមួយធនាគារ ឬអ្នកផ្តល់សេវាមុនធ្វើប្រតិបត្តិការ'],
    },
  },
}
