export type LanguageCode = 'th' | 'en' | 'lo' | 'my' | 'km'

export const SITE_URL = 'https://zrate.io'

export const LOCALES: LanguageCode[] = ['th', 'en', 'lo', 'my', 'km']

export const PAIRS = [
  'aed-thb',
  'aed-usd',
  'aud-thb',
  'aud-usd',
  'brl-thb',
  'brl-usd',
  'cad-thb',
  'cad-usd',
  'chf-thb',
  'chf-usd',
  'cny-thb',
  'cny-usd',
  'czk-thb',
  'czk-usd',
  'dkk-thb',
  'dkk-usd',
  'egp-thb',
  'egp-usd',
  'eur-gbp',
  'eur-jpy',
  'eur-thb',
  'eur-usd',
  'gbp-thb',
  'gbp-usd',
  'hkd-thb',
  'hkd-usd',
  'huf-thb',
  'huf-usd',
  'idr-thb',
  'idr-usd',
  'ils-thb',
  'ils-usd',
  'inr-thb',
  'inr-usd',
  'jpy-thb',
  'jpy-usd',
  'khr-thb',
  'khr-usd',
  'krw-thb',
  'krw-usd',
  'lak-thb',
  'lak-usd',
  'mmk-thb',
  'mmk-usd',
  'mxn-thb',
  'mxn-usd',
  'myr-lak',
  'myr-mmk',
  'myr-thb',
  'myr-usd',
  'ngn-thb',
  'ngn-usd',
  'nok-thb',
  'nok-usd',
  'nzd-thb',
  'nzd-usd',
  'php-thb',
  'php-usd',
  'pkr-thb',
  'pkr-usd',
  'pln-thb',
  'pln-usd',
  'rub-thb',
  'rub-usd',
  'sar-thb',
  'sar-usd',
  'sek-thb',
  'sek-usd',
  'sgd-myr',
  'sgd-thb',
  'sgd-usd',
  'thb-aed',
  'thb-aud',
  'thb-brl',
  'thb-cad',
  'thb-chf',
  'thb-cny',
  'thb-czk',
  'thb-dkk',
  'thb-egp',
  'thb-eur',
  'thb-gbp',
  'thb-hkd',
  'thb-huf',
  'thb-idr',
  'thb-ils',
  'thb-inr',
  'thb-jpy',
  'thb-khr',
  'thb-krw',
  'thb-lak',
  'thb-mmk',
  'thb-mxn',
  'thb-myr',
  'thb-ngn',
  'thb-nok',
  'thb-nzd',
  'thb-php',
  'thb-pkr',
  'thb-pln',
  'thb-rub',
  'thb-sar',
  'thb-sek',
  'thb-sgd',
  'thb-try',
  'thb-twd',
  'thb-usd',
  'thb-usdt',
  'thb-vnd',
  'thb-zar',
  'try-thb',
  'try-usd',
  'twd-thb',
  'twd-usd',
  'usd-aed',
  'usd-aud',
  'usd-brl',
  'usd-cad',
  'usd-chf',
  'usd-cny',
  'usd-czk',
  'usd-dkk',
  'usd-egp',
  'usd-eur',
  'usd-gbp',
  'usd-hkd',
  'usd-huf',
  'usd-idr',
  'usd-ils',
  'usd-inr',
  'usd-jpy',
  'usd-khr',
  'usd-krw',
  'usd-lak',
  'usd-mmk',
  'usd-mxn',
  'usd-myr',
  'usd-ngn',
  'usd-nok',
  'usd-nzd',
  'usd-php',
  'usd-pkr',
  'usd-pln',
  'usd-rub',
  'usd-sar',
  'usd-sek',
  'usd-sgd',
  'usd-thb',
  'usd-try',
  'usd-twd',
  'usd-vnd',
  'usd-zar',
  'usdt-thb',
  'usdt-usd',
  'vnd-thb',
  'vnd-usd',
  'zar-thb',
  'zar-usd'
] as const

export type PairSlug = typeof PAIRS[number]

export const FEATURED_PAIRS: PairSlug[] = [
  'usd-thb',
  'usdt-thb',
  'thb-lak',
  'thb-mmk',
  'thb-khr',
  'eur-thb',
]

export const REGIONAL_PAIRS: PairSlug[] = [
  'thb-lak',
  'thb-mmk',
  'thb-khr',
  'usd-lak',
  'usd-mmk',
  'usd-khr',
  'usd-sgd',
  'usd-myr',
  'usd-vnd',
  'usd-php',
  'usd-idr',
  'myr-lak',
  'myr-mmk',
]

export const STATIC_ROUTES = [
  '',
  '/rates',
  '/currency-pairs',
  '/money-transfer',
  '/blog',
  '/about',
  '/contact',
  '/privacy',
] as const

export const NAV_TEXT: Record<LanguageCode, {
  home: string
  rates: string
  pairs: string
  transfer: string
  blog: string
  about: string
  contact: string
  privacy: string
  disclaimer: string
  mainMenu: string
  popularPairs: string
  allPairs: string
  regionalPairs: string
  resources: string
  company: string
  legal: string
  liveRates: string
}> = {
  th: {
    home: 'แปลงค่าเงิน',
    rates: 'อัตราแลกเปลี่ยน',
    pairs: 'คู่เงิน',
    transfer: 'โอนเงิน',
    blog: 'บทความ',
    about: 'เกี่ยวกับเรา',
    contact: 'ติดต่อทีมงาน',
    privacy: 'นโยบายความเป็นส่วนตัว',
    disclaimer: 'ข้อจำกัดความรับผิดชอบ',
    mainMenu: 'เมนูหลัก',
    popularPairs: 'คู่เงินยอดนิยม',
    allPairs: 'คู่เงินทั้งหมด',
    regionalPairs: 'คู่เงินอาเซียน',
    resources: 'คู่มือและบทความ',
    company: 'เว็บไซต์',
    legal: 'ข้อมูลสำคัญ',
    liveRates: 'เรทสด',
  },
  en: {
    home: 'Converter',
    rates: 'Exchange Rates',
    pairs: 'Currency Pairs',
    transfer: 'Money Transfer',
    blog: 'Blog',
    about: 'About',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    disclaimer: 'Disclaimer',
    mainMenu: 'Main menu',
    popularPairs: 'Popular pairs',
    allPairs: 'All currency pairs',
    regionalPairs: 'ASEAN pairs',
    resources: 'Guides and articles',
    company: 'Website',
    legal: 'Important information',
    liveRates: 'Live rates',
  },
  lo: {
    home: 'ແປງເງິນ',
    rates: 'ອັດຕາແລກປ່ຽນ',
    pairs: 'ຄູ່ເງິນ',
    transfer: 'ໂອນເງິນ',
    blog: 'ບົດຄວາມ',
    about: 'ກ່ຽວກັບເຮົາ',
    contact: 'ຕິດຕໍ່',
    privacy: 'ນະໂຍບາຍຄວາມລັບ',
    disclaimer: 'ຂໍ້ຈຳກັດຄວາມຮັບຜິດຊອບ',
    mainMenu: 'ເມນູຫຼັກ',
    popularPairs: 'ຄູ່ເງິນຍອດນິຍົມ',
    allPairs: 'ຄູ່ເງິນທັງໝົດ',
    regionalPairs: 'ຄູ່ເງິນອາຊຽນ',
    resources: 'ຄູ່ມືແລະບົດຄວາມ',
    company: 'ເວັບໄຊ',
    legal: 'ຂໍ້ມູນສຳຄັນ',
    liveRates: 'ເຣດສົດ',
  },
  my: {
    home: 'ငွေကြေးပြောင်းစက်',
    rates: 'ငွေလဲနှုန်းများ',
    pairs: 'ငွေကြေးအတွဲများ',
    transfer: 'ငွေလွှဲ',
    blog: 'ဆောင်းပါးများ',
    about: 'ကျွန်ုပ်တို့အကြောင်း',
    contact: 'ဆက်သွယ်ရန်',
    privacy: 'ကိုယ်ရေးလုံခြုံရေးမူဝါဒ',
    disclaimer: 'ငြင်းဆိုချက်',
    mainMenu: 'အဓိက menu',
    popularPairs: 'လူကြိုက်များသော အတွဲများ',
    allPairs: 'ငွေကြေးအတွဲအားလုံး',
    regionalPairs: 'အာဆီယံအတွဲများ',
    resources: 'လမ်းညွှန်နှင့် ဆောင်းပါးများ',
    company: 'ဝဘ်ဆိုက်',
    legal: 'အရေးကြီးသော အချက်အလက်များ',
    liveRates: 'တိုက်ရိုက်နှုန်းများ',
  },
  km: {
    home: 'បម្លែងប្រាក់',
    rates: 'អត្រាប្តូរប្រាក់',
    pairs: 'គូរូបិយប័ណ្ណ',
    transfer: 'ផ្ទេរប្រាក់',
    blog: 'អត្ថបទ',
    about: 'អំពីយើង',
    contact: 'ទំនាក់ទំនង',
    privacy: 'គោលការណ៍ឯកជនភាព',
    disclaimer: 'ការបដិសេធ',
    mainMenu: 'ម៉ឺនុយសំខាន់',
    popularPairs: 'គូរូបិយប័ណ្ណពេញនិយម',
    allPairs: 'គូរូបិយប័ណ្ណទាំងអស់',
    regionalPairs: 'គូអាស៊ាន',
    resources: 'មគ្គុទ្ទេសក៍ និងអត្ថបទ',
    company: 'គេហទំព័រ',
    legal: 'ព័ត៌មានសំខាន់',
    liveRates: 'អត្រាផ្ទាល់',
  },
}

export const PAIR_LABELS: Record<PairSlug, string> = Object.fromEntries(
  PAIRS.map(pair => [pair, pair.toUpperCase().replace('-', '/')])
) as Record<PairSlug, string>

export function getLocalePrefix(lang: LanguageCode) {
  return lang === 'th' ? '' : `/${lang}`
}

export function localizePath(lang: LanguageCode, path: string) {
  const prefix = getLocalePrefix(lang)
  if (!path || path === '/') return prefix || '/'
  return `${prefix}${path}`
}
